"""Initial migration

Revision ID: ed12b6fab1cc
Revises: 
Create Date: 2026-01-26 16:51:18.742318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed12b6fab1cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('serving_size', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_items',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('caloriesKcal', sa.Float(), nullable=False),
    sa.Column('proteinG', sa.Float(), nullable=False),
    sa.Column('carbsG', sa.Float(), nullable=False),
    sa.Column('fatG', sa.Float(), nullable=False),
    sa.Column('fiberG', sa.Float(), nullable=False),
    sa.Column('sugarG', sa.Float(), nullable=False),
    sa.Column('sodiumMg', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_items')
    op.drop_table('meals')
    # ### end Alembic commands ###
